### ISSUE TITLE
Publish the Extension

### ISSUE THREAD

**Issue by ryanmerolle** [fredhsu/vscode-eos#2]
I think it would be useful to publish the extension for others to see in the market place.

What features, cleanup, or standardizing of "code" would you want to see before making this a reality?

https://code.visualstudio.com/api/working-with-extensions/publishing-extension
https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions (allowing you to push releases right from github)

**Comment by fredhsu** [comment]
@ryanmerolle Let me review this week and figure out what gaps we need to fill, but I'm good with just releasing it as a syntax highlighter until we can get more stuff in there.

**Comment by fredhsu** [comment]
Published to the marketplace! https://marketplace.visualstudio.com/items?itemName=aristapublisher.eos
